// Code generated by internal/generate. DO NOT EDIT.

package main

// An unreleased launcher: the release job replaces this file when it tags a version.
const version = ""

var archives = map[string]archive{}
